sensors:
  logical_camera_bins0:
    type: logical_camera
    pose:
      xyz: [4.04, 1.750927, 1.82]
      rpy: [0, 'pi/2', 0]

  logical_camera_bins1:
    type: logical_camera
    pose:
      xyz: [4.04, -1.750927, 1.82]
      rpy: [0, 'pi/2', 0]

  logical_camera_shelve1:
    type: logical_camera
    pose:
      xyz: [-4.093984, 3.176406, 2.49]
      rpy: [0, 'pi/2', 0]

  logical_camera_shelve2:
    type: logical_camera
    pose:
      xyz: [-4.093984, 0.078742, 2.49]
      rpy: [0, 'pi/2', 0]

  logical_camera_band:
    type: logical_camera
    pose:
      xyz: [0, 1.486, 1.7]
      rpy: [0, 'pi/2', 'pi/2']
